name: Issue to approved or request changes


on:
    pull_request_review:
        types: [submitted]

env:
    approved: Approved
    request_changes: Needs changes

jobs:
    approved:
        if: github.event.review.state == 'approved'
        runs-on: ubuntu-latest
        steps:
            - name: Extract Issue Number from PR Body
              id: extract_issue
              run: |
                issue_number=$(echo "${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | head -n 1 | tr -d '#')
                echo "ISSUE_NUMBER=$issue_number" >> $GITHUB_ENV
                echo "Extracted issue number: $issue_number"

            - name: Get Issue Node ID using GitHub REST API
              id: get_node_id
              run: |
                ISSUE_NODE_ID=$(curl -s \
                  -H "Authorization: token ${{ secrets.TEST_SECRET }}" \
                  "https://api.github.com/repos/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }}" | jq -r '.node_id')
                echo "ISSUE_NODE_ID=$ISSUE_NODE_ID" >> $GITHUB_ENV
                echo "Fetched Issue Node ID: $ISSUE_NODE_ID"

            - name: Move Issue to approved
              uses: leonsteinhaeuser/project-beta-automations@v2.1.0
              with:
                gh_token: ${{ secrets.TEST_SECRET }}
                organization: TofuBytes-Studies-Group
                project_id: 1
                resource_node_id: ${{ env.ISSUE_NODE_ID }}
                status_value: ${{ env.approved }}
    request_changes:
        if: github.event.review.state == 'changes_requested'
        runs-on: ubuntu-latest
        steps:
            - name: Extract Issue Number from PR Body
              id: extract_issue
              run: |
                issue_number=$(echo "${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | head -n 1 | tr -d '#')
                echo "ISSUE_NUMBER=$issue_number" >> $GITHUB_ENV
                echo "Extracted issue number: $issue_number"

            - name: Get Issue Node ID using GitHub REST API
              id: get_node_id
              run: |
                ISSUE_NODE_ID=$(curl -s \
                  -H "Authorization: token ${{ secrets.TEST_SECRET }}" \
                  "https://api.github.com/repos/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }}" | jq -r '.node_id')
                echo "ISSUE_NODE_ID=$ISSUE_NODE_ID" >> $GITHUB_ENV
                echo "Fetched Issue Node ID: $ISSUE_NODE_ID"

            - name: Move Issue to request changes
              uses: leonsteinhaeuser/project-beta-automations@v2.1.0
              with:
                gh_token: ${{ secrets.TEST_SECRET }}
                organization: TofuBytes-Studies-Group
                project_id: 1
                resource_node_id: ${{ env.ISSUE_NODE_ID }}
                status_value: ${{ env.request_changes }} 