name: Issue to In Review

on:
  pull_request:
    branches:
      - main

env:
  in_review: In review

jobs:
  in_review:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Extract Issue Number from PR Body
        id: extract_issue
        run: |
          issue_number=$(echo "${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | head -n 1 | tr -d '#')
          echo "ISSUE_NUMBER=$issue_number" >> $GITHUB_ENV
          echo "Extracted issue number: $issue_number"

      - name: Get Issue Node ID using GitHub REST API
        id: get_node_id
        run: |
          ISSUE_NODE_ID=$(curl -s \
            -H "Authorization: token ${{ secrets.TEST_SECRET }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }}" | jq -r '.node_id')
          echo "ISSUE_NODE_ID=$ISSUE_NODE_ID" >> $GITHUB_ENV
          echo "Fetched Issue Node ID: $ISSUE_NODE_ID"

      - name: Move Issue to ${{ env.in_review }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.TEST_SECRET }}
          organization: TofuBytes-Studies-Group
          project_id: 1
          resource_node_id: ${{ env.ISSUE_NODE_ID }}
          status_value: ${{ env.in_review }}

